# Project Euler
# Problem 2
# https://projecteuler.net/problem=2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fourMil = 4000000
count = 0
firstVal = 0
secondVal = 1
sum = 0

while count < fourMil:
    if count > 1 or count == 1:
        next = firstVal + secondVal
        if next % 2 == 0:
            sum += next
        firstVal = secondVal
        secondVal = next
    count =+ 1

print(sum)
